// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: common/proto/user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserRPCMethods_CheckUserExistenceByEmail_FullMethodName = "/UserRPCMethods/CheckUserExistenceByEmail"
)

// UserRPCMethodsClient is the client API for UserRPCMethods service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRPCMethodsClient interface {
	CheckUserExistenceByEmail(ctx context.Context, in *UserExistenceReq, opts ...grpc.CallOption) (*UserExistenceRep, error)
}

type userRPCMethodsClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRPCMethodsClient(cc grpc.ClientConnInterface) UserRPCMethodsClient {
	return &userRPCMethodsClient{cc}
}

func (c *userRPCMethodsClient) CheckUserExistenceByEmail(ctx context.Context, in *UserExistenceReq, opts ...grpc.CallOption) (*UserExistenceRep, error) {
	out := new(UserExistenceRep)
	err := c.cc.Invoke(ctx, UserRPCMethods_CheckUserExistenceByEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRPCMethodsServer is the server API for UserRPCMethods service.
// All implementations must embed UnimplementedUserRPCMethodsServer
// for forward compatibility
type UserRPCMethodsServer interface {
	CheckUserExistenceByEmail(context.Context, *UserExistenceReq) (*UserExistenceRep, error)
	mustEmbedUnimplementedUserRPCMethodsServer()
}

// UnimplementedUserRPCMethodsServer must be embedded to have forward compatible implementations.
type UnimplementedUserRPCMethodsServer struct {
}

func (UnimplementedUserRPCMethodsServer) CheckUserExistenceByEmail(context.Context, *UserExistenceReq) (*UserExistenceRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserExistenceByEmail not implemented")
}
func (UnimplementedUserRPCMethodsServer) mustEmbedUnimplementedUserRPCMethodsServer() {}

// UnsafeUserRPCMethodsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRPCMethodsServer will
// result in compilation errors.
type UnsafeUserRPCMethodsServer interface {
	mustEmbedUnimplementedUserRPCMethodsServer()
}

func RegisterUserRPCMethodsServer(s grpc.ServiceRegistrar, srv UserRPCMethodsServer) {
	s.RegisterService(&UserRPCMethods_ServiceDesc, srv)
}

func _UserRPCMethods_CheckUserExistenceByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserExistenceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRPCMethodsServer).CheckUserExistenceByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRPCMethods_CheckUserExistenceByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRPCMethodsServer).CheckUserExistenceByEmail(ctx, req.(*UserExistenceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRPCMethods_ServiceDesc is the grpc.ServiceDesc for UserRPCMethods service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRPCMethods_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserRPCMethods",
	HandlerType: (*UserRPCMethodsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUserExistenceByEmail",
			Handler:    _UserRPCMethods_CheckUserExistenceByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/user.proto",
}
